home/api/urls.py
from django.urls import path
from home.api import views

urlpatterns = [
    path('link/', views.link_list),
    path('link/<str:short_code>/', views.link_details),
    path('login/', views.login_view),
    path('logout/', views.logout_view)

]

home/urls.py
from django.urls import path, include
from home import views


urlpatterns = [
    path('', views.index, name='home'),
    path('api/', include('home.api.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('<str:short_code>/delete', views.delete_link, name='delete_link'),
    path('<str:short_code>/', views.redirect_user, name='redirect'),
]

shortayn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home'))
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Link(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    short_code = models.CharField(max_length=30, unique=True)
    redirect_to = models.URLField(blank=False, null=False)
    amount_of_visits = models.IntegerField(default=0)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.short_code

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from home import models


class LinkForm(forms.ModelForm):
    class Meta:
        model = models.Link
        exclude = ('amount_of_visits', 'user', 'time_created')


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

home/api/views.py
from home.api.serializers import LinkSerializer, LoginSerializer
from home.models import Link
from rest_framework.decorators import api_view
from django.views.decorators.csrf import csrf_exempt
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from django.http.response import JsonResponse, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from rest_framework import status


@api_view(['GET', 'POST'])
def link_list(request):

    if request.method == 'GET':
        data = Link.objects.all()
        serializer = LinkSerializer(data, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    if request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = LinkSerializer(data=data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['DELETE', 'GET'])
def link_details(request, short_code):
    try:
        link = Link.objects.get(short_code=short_code)
    except Link.DoesNotExist:
        return HttpResponse(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'DELETE':
        link.delete()
        return Response(status=status.HTTP_200_OK)
    elif request.method == 'GET':
        serializer = LinkSerializer(link)
        return Response(serializer.data, status=status.HTTP_200_OK)


@api_view(['POST'])
def login_view(request):
    if request.method == 'POST':
        data = JSONParser().parse(request)
        print(data)
        serializer = LoginSerializer(data=data)
        print(serializer.initial_data)
        if serializer.is_valid():
            user = User.objects.get(email=serializer.data['email'])
            user = authenticate(username=user.username, password=serializer.data['password'])
            if user is not None:
                login(request, user)
                return Response(status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def logout_view(request):
    if request.method == 'GET':
        logout(request)
        return Response(status=status.HTTP_200_OK)

home/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):

    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('home:dashboard')
        else:
            return render(request, 'home/index.html')



def redirect_user(request, short_code):
    from .models import Link
    url = Link.objects.get(short_code=short_code)
    url.amount_of_visits += 1
    url.save()
    return redirect(url.redirect_to)



def login_view(request):

    if request.method == 'GET':
        return render(request, 'home/login.html')

    else:
        email = request.POST.get('email')
        password = request.POST.get('password')
        try:
            user = User.objects.get(email=email.lower())
            user = authenticate(username=user.username, password=password)
            login(request, user)
            return redirect('home:home')
        except:
            messages.add_message(request, messages.WARNING, 'email or password is incorrect')
            return redirect('home:login')


def signup_view(request):
    if request.method == 'GET':
        from home.forms import RegistrationForm
        form = RegistrationForm
        args = {'form': form}
        return render(request, 'home/signup.html', args)
    else:
        from home.forms import RegistrationForm
        form = RegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.filter(email=email)
            if user.count() == 0:
                saved = form.save(commit=False)
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                saved.email = form.cleaned_data['email'].lower()
                saved.save()
                user = authenticate(username=username, password=password)

                if user is not None:
                    if user.is_active:
                        login(request, user)
                        return redirect('home:home')
            else:
                messages.add_message(request, messages.ERROR, 'email has already been used')
                return render(request, 'home/signup.html', {'form': form})
        else:
            return render(request, 'home/signup.html', {'form': form})


@login_required
def dashboard(request):
    from .forms import LinkForm
    from .models import Link
    from ipaddr import client_ip
    import requests
    if request.method == 'GET':
        form = LinkForm()
        links = Link.objects.filter(user=request.user)
        total_clicks = 0
        for link in links:
            total_clicks += link.amount_of_visits
        ##client_address = client_ip(request)
        #response = requests.get("http://ip-api.com/json/"+ client_address)
        args = {'form': form, 'links': links, 'total_clicks': total_clicks} #'ip_data':response.json()}

        return render(request, 'home/dashboard.html', args)
    else:
        form = LinkForm(request.POST)
        if Link.objects.filter(user = request.user).count() <= 4:
            if form.is_valid:
                saved = form.save(commit=False)
                saved.user = request.user
                saved.save()
                return redirect('home:home')
        else:
            messages.add_message(request, messages.ERROR, 'You cannot hav more than 5 links')
            return redirect('home:dashboard')



def logout_view(request):
    from django.contrib.auth import logout
    logout(request)
    return redirect('home:home')


def delete_link(request, short_code):
    from home.models import Link
    link = Link.objects.get(short_code=short_code)
    link.delete()
    return redirect('home:home')

home/templates/home/base.html
{% load widget_tweaks %}
{% load staticfiles %}
<html>
    <head>
        <meta charset="UTF-8">
        <link href="{% static 'home/css/img/shortayn.png' %}" rel="shortcut icon" type="image/x-icon" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
        <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,300italic' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/grid.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">


        <title> Shortayn </title>
    </head>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#"><h1> <ion-icon name="pulse"></ion-icon>  Shortayn</h1></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% if not user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home' %}#how">How to Use</a>
              </li>


              <li class="nav-item ">
                <a class="nav-link" href="{% url 'home:signup' %}">Sign Up</a>
              </li>

               <li class="nav-item">
                <a class="nav-link" href="{% url 'home:login' %}">Login</a>
              </li>


            </ul>
            {% else %}
            <ul class="navbar-nav mr-auto searchbar">

                <li class="nav-item  signout" data-toggle="tooltip" data-placement="top" title="Sign Out">

                     <a class="nav-link" href="{% url 'home:logout' %}">  <ion-icon size="large" name="log-out"></ion-icon>   </a>
               </li>

            </ul>
            {% endif %}
        </div>
    </nav>
    <body>
        {% block body %}
        {% endblock %}

    <!-- Bootstrap Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/ionicons@4.4.4/dist/ionicons.js"></script>
    </body>

</html>

home/templates/home/dashboard.html
{% extends 'home/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block body %}

    <div class="jumbotron summary">
        <div class="row">
            <div class="col span-1-of-4">
                <div class="number_of icon row">
                    <ion-icon name="contact"></ion-icon>
                </div>
                <div class=" number_of row">
                   {{ request.user.username }}
                </div>
                <div class=" desc row">
                    USERNAME
                </div>

            </div>



            <div class="col span-1-of-4">
                <div class="number_of icon row">
                    <ion-icon name="stats"></ion-icon>
                </div>
                <div class=" number_of row">
                    {{ total_clicks }}
                </div>
                <div class=" desc row">
                    CLICKS
                </div>

            </div>

            <div class="col span-1-of-4">
                <div class="number_of icon row">
                    <ion-icon name="link"></ion-icon>
                </div>
                <div class=" number_of row">
                    {{ links.count }}
                </div>
                <div class=" desc row">
                    LINKS CREATED
                </div>

            </div>
            <div class="col span-1-of-4">
                <div class="number_of icon row">
                    <ion-icon name="pin"></ion-icon>
                </div>
                <div class=" number_of row">
                     {{ ip_data.country }}
                </div>
                <div class=" desc row">
                    LOCATION
                </div>

            </div>

        </div>


    </div>
    <section class="links">
        <div class="row">
            <div class="col span-1-of-5 shortened">
                <div class="row">
                    <h3> Shortened  </h3>
                </div>
                <hr>
                {% for link in links %}
                <div class="row">
                        <div class="card">
                                <div class="card-body">
                                  <h5 class="card-title"> {{ link.short_code }}</h5>
                                  <h6 class="card-subtitle mb-2 text-muted">{{ link.time_created }}</h6>
                                  <p class="card-text">{{ link.redirect_to }}</p>
                                  <a href="http://shortayn.herokuapp.com/{{ link.short_code }}" target="_blank" class="card-link">shortayn.herokuapp.com/{{ link.short_code }}</a>
                                  <br>
                                  <p>
                                    <ion-icon name="stats"></ion-icon>  {{ link.amount_of_visits }} CLICKS
                                  </p>
                                    <p><a href="{% url 'home:delete_link' link.short_code %}">delete link</a> </p>

                                </div>
                              </div>

                </div>
                {% endfor %}



            </div>
            <div class="col span-4-of-5">
                <div class="row">
                    <h3> Shorten </h3>
                </div>
                <form action="" method="post">
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <!--<label for="formGroupExampleInput"> Short Code </label>-->
                        <br>
                        {{ form.short_code|attr:"class:form-control"|attr:"id:formGroupExampleInput2"|attr:"placeholder:Link title" }}

                    </div>
                    <div class="form-group">
                        {{ form.redirect_to|attr:"class:form-control"|attr:"id:formGroupExampleInput2"|attr:"placeholder:Link to be Shortened" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Shorten</button>
                </form>
            </div>
        </div>
    </section>



{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load staticfiles %}


{% block body %}
	<header>

	
	<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h2 class="display-4">HARNESS EVERY CLICK</h2>
    <p class="lead">Get shorter links with Shortayn. </p>
    <p class="lead">
        <a href="{% url 'home:signup' %}">
    <button type="button" class="btn btn-primary">GET STARTED TODAY</button>
        </a>
	</p>
  </div>
</div>
		
</header>
<section class="how" id="how">
	<h3> How To Use</h3>

    <div class="row padd">
        <div class="col span-1-of-3">
            <div class="row  how_icon">
                <ion-icon size="large" name="log-in"></ion-icon>
            </div>
            <div class="row ">
          - Sign up and Login
            </div>

        </div>

        <div class="col span-1-of-3">
            <div class="row how_icon">

                <ion-icon size="large" name="cut"></ion-icon>
            </div>
            <div class="row">
           -    Copy  URL of the page.
            </div>

        </div>



        <div class="col span-1-of-3">
            <div class="row how_icon">
                <ion-icon size="large" name="copy"></ion-icon>
            </div>
             <div class="row">
              - Paste the URL and click  <b> Shorten.</b>
            </div>

        </div>
    </div>

</section>



<div class="jumbotron jumbotron-fluid footer_sec">
  <div class="container">

    <p class="footer"> Copyright &copy;  Shortayn 2019. All rights reserved.Privacy policy.</p>
  </div>
</div>
{% endblock %}

	<!-- Bootstrap Scripts -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/ionicons@4.4.4/dist/ionicons.js"></script>

</html>

home/templates/home/logged_in_base.html
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,300italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/grid.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'home/css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">


    <title> Shortayn </title>
</head>

home/templates/home/login.html
{% load staticfiles %}
{% load widget_tweaks %}
{% include 'home/base.html' %}


{% block body %}
<header>

<div class ="login_card ">

		<h4> Login </h4>
	<div class="container login-form">
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post">
    {% csrf_token %}
  <div class="form-group">
{#    <label for="exampleInputEmail1">Email address</label>#}
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter Email">
    
  </div>
  <div class="form-group">
{#    <label for="exampleInputPassword1">Password</label>#}
    <input type="password" class="form-control" id="password1" name="password" placeholder="Password">
  </div>
 
  <button type="submit" class="btn btn-primary">Login</button>
</form> 
		
	</div>
</div>
	
	
</header>
{% endblock %}

home/templates/home/signup.html
{% extends 'home/base.html' %}
{% load widget_tweaks %}
{% block body %}
<header>


<div class ="signin_card ">

		<h4> Sign Up </h4>
	<div class="container login-form">
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post">
    {% csrf_token %}
    <div class="form-group">

      {{ form.username|attr:"class:form-control"|attr:"aria-describedby:emailHelp"|attr:"placeholder:Username" }}
    </div>
    <div class="form-group">

      {{ form.first_name|attr:"class:form-control"|attr:"aria-describedby:emailHelp"|attr:"placeholder:First Name" }}
  </div>
  <div class="form-group">
    
      {{ form.last_name|attr:"class:form-control"|attr:"aria-describedby:emailHelp"|attr:"placeholder:Last Name" }}
    
  </div>
  <div class="form-group">
    
      {{ form.email|attr:"class:form-control"|attr:"aria-describedby:emailHelp"|attr:"placeholder:Enter email" }}
    
  </div>
  <div class="form-group">
    
      {{ form.password1|attr:"class:form-control"|attr:"placeholder:Password" }}

  </div>
  <div class="form-group">
    
      {{ form.password2|attr:"class:form-control"|attr:"placeholder:Confirm Password" }}

  </div>
 
  <button type="submit" class="btn btn-primary">Sign Up</button>
</form> 
		
	</div>

</div>
	
</header>
{% endblock %}